version: '3'

services:
  redis:
    image: redis
    container_name: redis_blogger
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
    env_file:
      - .env

  rabbitmq:
    image: 'rabbitmq:3.10-management'
    container_name: rabbitmq_blogger
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

