DROP DATABASE IF EXISTS postgres;
DROP DATABASE IF EXISTS api_registry;
DROP DATABASE IF EXISTS user_service;
DROP DATABASE IF EXISTS blogger;
CREATE DATABASE postgres;
CREATE DATABASE api_registry;
CREATE DATABASE user_service;
CREATE DATABASE blogger;
