/* eslint-disable */
/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! GENERATED FILE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * (autogenerated by generateApiFactoryClass.js)
 */

 import {BloggerServiceApi} from './api';
import {CommentsServiceApi} from './api';
import {GraphQLServiceApi} from './api';
import {UserServiceApi} from './api';
import {VotesServiceApi} from './api';


/**
 * This class provides methods to create specific apis
 */
export default class ApiFactory {

    public static createBloggerServiceApi() {
      return new BloggerServiceApi();
    }

    public static createCommentsServiceApi() {
      return new CommentsServiceApi();
    }

    public static createGraphQLServiceApi() {
      return new GraphQLServiceApi();
    }

    public static createUserServiceApi() {
      return new UserServiceApi();
    }

    public static createVotesServiceApi() {
      return new VotesServiceApi();
    }
}